name: gitleaks

on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Escanear secretos con gitleaks
        run: docker run -v ${{ github.workspace }}:/repo zricethezav/gitleaks:latest detect --source="/repo" -v
